sources:
  - Kanz-al-Marjaan.designspace
familyName: "Kanz-al-Marjaan"

buildVariable: true
buildStatic: true
buildTTF: false
buildOTF: false

stat:
  Kanz-al-Marjaan[wght].ttf:
    - name: Weight
      tag: wght
      values:
        - name: Regular
          value: 400
          flags: 2