sources:
  - Kanz-al-Marjaan-Regular.ufo

familyName: "Kanz-al-Marjaan"

outputDir: fonts
vfDir: fonts/variable
ttfDir: fonts/ttf    # Change from ttDir to ttfDir (what gftools expects)
otfDir: fonts/otf

buildVariable: false
buildStatic: true
buildTTF: true
buildOTF: false

includeSourceFixes: true

stat:
  Kanz-al-Marjaan-Regular.ttf:
    - name: Weight
      tag: wght
      values:
      - name: Regular
        value: 400
