sources:
  - Kanz-al-Marjaan-Regular.ufo

familyName: "Kanz-al-Marjaan"

outputDir: fonts
vfDir: $outputDir/variable
ttDir: $outputDir/ttf
otDir: $outputDir/otf

buildVariable: false  # Changed to false since we're building from UFO directly
buildStatic: true    # Changed to true since we're building static fonts
buildTTF: true
buildOTF: false

includeSourceFixes: true

stat:
  Kanz-al-Marjaan-Regular.ttf:
    - name: Weight
      tag: wght
      values:
      - name: Regular
        value: 400