sources:
  - Kanz-al-Marjaan.designspace
familyName: "Kanz-al-Marjaan"

output:
  - variable
buildVariable: false
buildStatic: false

stat:
  Kanz-al-Marjaan[wght].ttf:
    - name: Weight
      tag: wght
      values:
      - name: Regular
        value: 400
        flags: 2